name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Docker Image
      - name: Build Docker image
        run: docker build -t task-manager .